apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: "LoadBalancer"
  ports:
    - targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
      port: 80
  selector:
    app: {{ .Values.name }}
