name: Deploy App

on:
  # workflow_run:
  #   workflows: ["Test App", "Deploy Infrastructure"]
  #   branches: [main]
  #   types:
  #     - completed
  push:

jobs:
  build:
    - run: echo "running"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: us-central1-docker.pkg.dev/k8-deploy-338617/app/backend:$(git rev-parse --short HEAD)
